export const ENGINE_DEBUG_MODE: boolean = false;
export const GAME_DEBUG_MODE: boolean = false;

export const DEFAULT_TEXTURE_B64 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAAAAYSURBVBhXY/gf8P8/AwPDf0YQ8T/gPwMASMgHm0SkFZgAAAAASUVORK5CYII=`;

export const DEFAULT_CAMERA_FOV: number = 40;
