export const GAME_DEBUG_MODE: boolean = true;
export const ENGINE_DEBUG_MODE: boolean = true;
export const ANALYTICS_DEBUG_MODE = ENGINE_DEBUG_MODE;
export const AD_DEBUG = ENGINE_DEBUG_MODE;

export const DEFAULT_TEXTURE_B64 =
    `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAAC` +
    `CAYAAABytg0kAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAA` +
    `AJcEhZcwAADsIAAA7CARUoSoAAAAAYSURBVBhXY/gf8P8/AwPDf0YQ` +
    `8T/gPwMASMgHm0SkFZgAAAAASUVORK5CYII=`;

export const DEFAULT_CAMERA_FOV: number = 40;
